/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sina_shopguide_util_SecretParams */

#ifndef _Included_com_sina_shopguide_util_SecretParams
#define _Included_com_sina_shopguide_util_SecretParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sina_shopguide_util_SecretParams
 * Method:    getHttpTransMd5Key
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sina_shopguide_util_SecretParams_getHttpTransMd5Key
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sina_shopguide_util_SecretParams
 * Method:    getHttpTransSource
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sina_shopguide_util_SecretParams_getHttpTransSource
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
